embedding:
  type: "transformer"
  config:
    model_name: "mrm8488/bert-base-spanish-wwm-cased-finetuned-spa-squad2-es"
    # "bert-base-multilingual-uncased" 
    # "bert-base-multilingual-cased" 
    # "gamallo/bert-base-gl-cased-finetuned"
    # "gamallo/bert-base-gl-cased-finetuned-cola"
    # "gamallo/distilbert-base-uncased-finetuned-cola"
    # "hiiamsid/sentence_similarity_spanish_es"
    # "dccuchile/bert-base-spanish-wwm-cased"
    # "dccuchile/bert-base-spanish-wwm-uncased"
    # "PlanTL-GOB-ES/roberta-base-bne"
    # "mrm8488/bert-base-spanish-wwm-cased-finetuned-spa-squad2-es"
    max_length: 512
  training_data_path: "data/bc_datos.xlsx"

ingestion:
  chunk_size: 1000
  chunk_overlap: 200

evaluation:
  articles_file: "data/bc_datos.xlsx"
  rankings_file: "data/querys simples.txt"

mlflow:
  experiment_name: "Transformer Evaluation"

search:
  types_to_evaluate: ['vector', 'keyword', 'hybrid']
  default_type: hybrid
  hybrid:
    vector_weight: 0.7
    keyword_weight: 0.3